### ISSUE TITLE
the recoverpy run failed.

### ISSUE THREAD

**Issue by lylklb** [PabloLec/recoverpy#2]
Although all the py-cui/pyaml/recoverpy were installed successfully, the recoverpy still run failed.
Notes: py-cui 0.1.3 & pyaml 5.4.1

Might it be due to the cycle import dependency modules within the following *.py files:

# python3 -m recoverpy
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib64/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3.6/site-packages/recoverpy/__init__.py", line 15, in <module>
    import recoverpy.window_handler as WINDOW_HANDLER
  File "/usr/lib/python3.6/site-packages/recoverpy/window_handler.py", line 3, in <module>
    import recoverpy.parameters_menu as PARAMETERS_MENU
  File "/usr/lib/python3.6/site-packages/recoverpy/parameters_menu.py", line 7, in <module>
    import recoverpy.window_handler as WINDOW_HANDLER
AttributeError: module 'recoverpy' has no attribute 'window_handler'

**Comment by PabloLec** [comment]
Hi, thanks for the heads up !

These imports statement should not cause circular imports as they are absolute imports and being object-oriented modules, their classes and methods are only used once fully loaded, nothing is run top level.

Nonetheless, I can't reproduce this error, but I do have errors on install with python 3.6, probably because of my venv.
Just reinstalled current version in venvs with 3.8 and 3.9 and recoverpy seems to run fine.

Can you try the following commands and give me the output :

```bash
python3 -V
git clone https://github.com/PabloLec/recoverpy.git
cd recoverpy
python3 -m venv env
source env/bin/activate
python3 -m pip install .
```

And then, still in your venv, try to run `python3 -m recoverpy`.

**Comment by PabloLec** [comment]
Just tried with python 3.6 and I do indeed have the same errors. Don't bother trying to reinstall, I'm working on it :wrench::wink:

**Comment by PabloLec** [comment]
Ok, that's fixed !
Just released the updated version, install with Github or directly via pip.

@lylklb Please let me know if you have any error with new version. It's working fine with 3.6 from what I can see.

**Comment by lylklb** [comment]
I have just tried with your new release 1.0.1,  the result is the following new error.
And it seems that the problem might be due to the python 3.6 library curses 。。。?

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/site-packages/recoverpy/__main__.py", line 3, in <module>
    recoverpy.main()
  File "/usr/lib/python3.6/site-packages/recoverpy/__init__.py", line 42, in main
    WINDOW_HANDLER.open_parameters_menu()
  File "/usr/lib/python3.6/site-packages/recoverpy/window_handler.py", line 21, in open_parameters_menu
    _PARAMETERS_MENU.start()
  File "/usr/lib/python3.6/site-packages/py_cui-0.1.3-py3.6.egg/py_cui/__init__.py", line 317, in start
  File "/usr/lib64/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python3.6/site-packages/py_cui-0.1.3-py3.6.egg/py_cui/__init__.py", line 1493, in _draw
  File "/usr/lib/python3.6/site-packages/py_cui-0.1.3-py3.6.egg/py_cui/__init__.py", line 374, in _initialize_colors
_curses.error: init_color() returned ERR

**Comment by PabloLec** [comment]
I'm not sure if it's curses' fault or terminal's.

There seems to be similar issues with old versions of putty.

Can you please tell me what terminal are you using and its version ?
Also, can you provide the output of `echo $TERM` ?

I'll try to reproduce this error and open a new issue.

**Comment by lylklb** [comment]
SecureCRT 6.2~8.7、 Xmanager/Xshell 5

```
# echo $TERM
vt100
#
```

**Comment by PabloLec** [comment]
I opened a new issue #3 for this. And I think I see the problem.

**Comment by lylklb** [comment]
Could you please tell why the older 1.0.1 version would only run failed under the python 3.6 environment ？

**Comment by PabloLec** [comment]
This PR seems to be the cause: https://github.com/python/cpython/pull/1264

Prior to 3.7, things like:
`submodule1.py`
```python
import module.submodule2 as b
``` 

`submodule2.py`
```python
import module.submodule1 as a
``` 

Were considered as circular imports, now it is supported. (As long as these absolute imports are binded to another name, like `a` or `b` in my example)

**Comment by lylklb** [comment]
So at the first time,  I doubt this problem might be due to the cycle import modules。。。
